/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimpleViewRouteImport } from './routes/simpleView'
import { Route as AdvancedViewRouteImport } from './routes/advancedView'
import { Route as IndexRouteImport } from './routes/index'

const SimpleViewRoute = SimpleViewRouteImport.update({
  id: '/simpleView',
  path: '/simpleView',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedViewRoute = AdvancedViewRouteImport.update({
  id: '/advancedView',
  path: '/advancedView',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advancedView': typeof AdvancedViewRoute
  '/simpleView': typeof SimpleViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advancedView': typeof AdvancedViewRoute
  '/simpleView': typeof SimpleViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advancedView': typeof AdvancedViewRoute
  '/simpleView': typeof SimpleViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/advancedView' | '/simpleView'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/advancedView' | '/simpleView'
  id: '__root__' | '/' | '/advancedView' | '/simpleView'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvancedViewRoute: typeof AdvancedViewRoute
  SimpleViewRoute: typeof SimpleViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simpleView': {
      id: '/simpleView'
      path: '/simpleView'
      fullPath: '/simpleView'
      preLoaderRoute: typeof SimpleViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advancedView': {
      id: '/advancedView'
      path: '/advancedView'
      fullPath: '/advancedView'
      preLoaderRoute: typeof AdvancedViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvancedViewRoute: AdvancedViewRoute,
  SimpleViewRoute: SimpleViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
